### ISSUE TITLE
Octopus all_rates attribute warning

### ISSUE THREAD

**Issue by zaheerm** [springfall2008/batpred#1684] opened 2024-12-03 09:36 UTC
**Describe the bug**

Log shows:

```
2024-12-03 09:30:04.507396: Warn: No Octopus data in sensor sensor.electricity_<meter>_previous_rate attribute 'all_rates'
2024-12-03 09:30:04.507507: Warn: No Octopus data in sensor event.electricity_<meter>_current_day_rates attribute 'all_rates' / 'rates' / 'raw_today'
2024-12-03 09:30:04.507691: Error: metric_octopus_import is not set correctly or no energy rates can be read
2024-12-03 09:30:04.547027: Warn: record_status Error: metric_octopus_import not set correctly or no energy rates can be read
2024-12-03 09:30:04.547354: Error: Exception raised 
2024-12-03 09:30:04.547909: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 959, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 529, in update_pred
    self.fetch_sensor_data()
  File "/config/fetch.py", line 825, in fetch_sensor_data
    raise ValueError
ValueError
```

**Expected behaviour**

**Predbat version**

Latest (zip file shows 8.8.1)

**Environment details**

- GivTCP inverter and battery
- Standard HAOS installer 
- Octopus integration latest version

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by gcoan** [comment] 2024-12-03 17:37
Is this a new install or an upgrade?

Are the Octopus sensors that Predbat is looking for populated correctly and what's in your apps.yaml, is Predbat configured correctly to find the Octopus sensors?

If its a new install, you follow the instructions about enabling specific events that Predbat needs

**Comment by zaheerm** [comment] 2024-12-03 19:13
<img width="581" alt="Screenshot 2024-12-03 at 19 13 10" src="https://github.com/user-attachments/assets/9c31b335-6a45-4edb-b7d3-55666b34dbb6">
is a screenshot of my home-assistant current_day_rates event sensor.

**Comment by gcoan** [comment] 2024-12-03 19:18
Thanks for the extra info.  The apps.yaml looks correct. 

If you look at the sensor sensor.octopus_energy_electricity_MPAN_METERSERIAL_current_rate what do you see, is it populated OK?

Can you share your logfile please, am guessing it's either a problem with not picking up your Octopus details properly.

**Comment by gcoan** [comment] 2024-12-03 19:19
> is a screenshot of my home-assistant current_day_rates event sensor.

Looks like the event is firing OK.  Let's see what's in the actual import sensor

**Comment by zaheerm** [comment] 2024-12-03 19:33
https://gist.github.com/zaheerm/f550ffb3f766ce2eec4855faee9
<img width="575" alt="Screenshot 2024-12-03 at 19 32 46" src="https://github.com/user-attachments/assets/b9cdaed3-f8cc-46cd-9c9b-a58296bf8bc6">
c8c53 is the log file

**Comment by zaheerm** [comment] 2024-12-03 19:34
<img width="573" alt="Screenshot 2024-12-03 at 19 34 27" src="https://github.com/user-attachments/assets/c5c47f2f-546f-4644-bf97-752815d8e13a">
when expanding attributes

**Comment by springfall2008** [comment] 2024-12-03 20:28
There's something wrong here as the Event shown doesn't have the mpan in its name?

**Comment by gcoan** [comment] 2024-12-03 20:57
I think the problem is that your import energy sensor is named in a way that Predbat doesn't expect.

From the logfile it finds your import sensor:

2024-12-03 09:02:10.818563: Regular expression argument metric_octopus_import matched ^(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_rate)$ with sensor.electricity_METER_NUMBER_current_rate

Whereas on mine the sensor name is sensor.octopus_energy_electricity_METER_NUMBER_current_rate

Predbat uses the import sensor to then find the names of other sensors it needs, and it's not finding them.  Guessing that there is a mis-match and the other sensors have the octopus_energy_ prefix whereas current_rate doesn't.

Did you rename this sensor?

Simplest thing to try is to rename the sensor you have to the name it should normally be.  If you want to rename it then you'll also need to rename the other sensors that Predbat is looking for so they all have matching name structure

**Comment by zaheerm** [comment] 2024-12-03 21:35
Good spot, All my sensors seem to be sensor.electricty_ while my events seem to be event.octopus_energy_electricity. I may set the sensors and events manually in predbat config and give that a go rather than doing renames.

**Comment by gcoan** [comment] 2024-12-04 00:39
👍

I think that's your problem.  Without checking the code I think Predbat expects the events and sensors to be named consistently.  You may have to do some renaming.

Curious as to why your new install ended up like this.  Maybe something changed in the Octopus Integration

**Comment by zaheerm** [comment] 2024-12-07 09:23
Thanks @gcoan I ended up renaming the sensors to make them consistent once i spotted nothing else was using them. This solved my issue, shall I close?

**Comment by gcoan** [comment] 2024-12-07 18:17
@zaheerm glad you've got it working OK.  Weird that your entities had different names.

Are you seeing any warnings in the predbat log about all_rates not existing on the sensor still?

There's another issue that has been raised #1699 about all_rates warning, which from what I can see doesn't exist as an attribute so wondered if you were seeing the same warning as well?

At least we got yours working now

**Comment by zaheerm** [comment] 2024-12-07 18:20
I am not seeing any more warnings at all. I saw that issue come in and looked for any similar patterns here but don't see it.

**Comment by gcoan** [comment] 2024-12-07 22:15
Ok thanks for confirming, sounds like can close this issue now then

**Closed** 2024-12-07 22:23 UTC
