### ISSUE TITLE
Changing mode does not stop/interrupt the current mode

### ISSUE THREAD

**Issue by DJBenson** [springfall2008/batpred#513] opened 2023-12-21 16:20 UTC
**Describe the bug**
When the mode is changed from say "Control charge & discharge" to "Control charge" and there is an active discharge action, that action is not interrupted.

**Expected behavior**
I would expect Predbat to respond to such a change by stopping the export immediately. The only way I could get the system to stop discharging was by modifying GivTCP settings directly (turned off timed export).

**Predbat version**
7.14.19

**Environment details**

- GivEnergy AIO
- HAOS (up to date)

**Comment by springfall2008** [comment] 2023-12-22 10:32
I can see the confusion, I'm afraid this is kind of by design in that if Predbat is not set to control discharge then it won't control them. 

I suspect I could do something to cancel discharge when the mode is changed for safety reasons so will keep this ticket open while I think on it. The same issue applies to read-only mode where the current charge/discharge will be left as-is.

**Comment by DJBenson** [comment] 2023-12-22 10:38
Thanks Trefor. For the less advanced user I could see this causing panic as it's not immediately obvious how to stop the export.

**Comment by springfall2008** [comment] 2023-12-23 19:54
Fixed in the current release

**Closed** 2023-12-26 09:23 UTC
